name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 'head'
            gemfile: 'latest'
          - ruby: '3.3'
            gemfile: 'latest'
          - ruby: '3.1'
            gemfile: 'latest'
          - ruby: '2.7'
            gemfile: 'old'
          - ruby: '2.6'
            gemfile: 'old'
          - ruby: 'jruby-9.4.9'
            gemfile: 'old'
          - ruby: 'truffleruby-24.1.1'
            gemfile: 'latest'
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      CC_TEST_REPORTER_ID: 7edce7eef3cd081f99ae25d8ae8e7c1d220a9b1cd2d5200cbbb361e5bc8598f4

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install codespell
      if: startsWith(matrix.ruby, '3.3')
      run: |
        python -m pip install --upgrade pip
        pip install codespell==2.3.0
    - name: Check spelling with codespell
      if: startsWith(matrix.ruby, '3.3')
      run: codespell --skip='./sig,./doc,./coverage,./vendor' || exit 1

    - name: Check Code Standards
      if: startsWith(matrix.ruby, '3.3')
      run: bundle exec rubocop

    - name: Markdown linter
      if: startsWith(matrix.ruby, '3.3')
      run: bundle exec mdl README.md CHANGELOG.md RELEASE.md

    - name: Run Tests
      run: bundle exec rspec

    # https://github.com/paambaati/codeclimate-action
    - name: Publish code coverage to code-climate
      uses: paambaati/codeclimate-action@v9.0.0
      if: (github.event_name == 'push') && startsWith(matrix.ruby, '3.3')
